initPos: [148.5, 116, 319.5]
gameTipShowTime: 10
rankUpdateTime: 30

#shop config
shop:
    -
        type: 0
        icon: "set:items_gui.json image:diamond"
        name: "gui.shop.tab.diamond"
        goods:
            -
                desc: "jail_item_name_cash1700"
                price: [10000, 0, 1700, 1, 5, 100, -1]
            -
                desc: "jail_item_name_cash5000"
                price: [10000, 0, 5000, 1, 15, 300, -1]
            -
                desc: "jail_item_name_cash10000"
                price: [10000, 0, 10000, 1, 27, 540, -1]
            -
                desc: "jail_item_name_cash20000"
                price: [10000, 0, 20000, 1, 55, 1100, -1]
    -
        type: 1
        icon: "set:items_gui.json image:keyToDoor"
        name: "gui.shop.tab.others"
        goods:
            -
                desc: "gui_bullet_name_1.name"
                price: [441, 0, 20, 3, 20, 20, -1]
            -
                desc: "gui_bullet_name_2.name"
                price: [442, 0, 30, 3, 45, 45, -1]
            -
                desc: "gui_bullet_name_3.name"
                price: [443, 0, 45, 3, 90, 90, -1]
            -
                desc: "gui_bullet_name_5.name"
                price: [446, 0, 10, 3, 100, 100, -1]
            -
                desc: "item.bread.name"
                price: [297, 0, 5, 3, 50, 50, -1]
            -
                desc: "item.beefCooked.name"
                price: [364, 0, 5, 3, 100, 100, -1]
            -
                desc: "item.potion_heal.name"
                price: [517, 0, 1, 3, 150, 150, -1]
            # -
                # desc: "item.potion_jump.name"
                # price: [514, 0, 1, 3, 200, 200, -1]
            # -
                # desc: "item.potion_invisibility.name"
                # price: [512, 0, 1, 1, 2, 40, -1]
            # -
                # desc: "item.potion_move_speed.name"
                # price: [521, 0, 1, 3, 150, 150, -1]
                
#weapon config
weapon:
    gun:
    # 手枪
        -
            id: 426
            damage: 3
            bulletId: 441
            maxBulletNum: 20
            knockback: 0
    #步枪
        -
            id: 427
            damage: 4
            bulletId: 442
            maxBulletNum: 30
            knockback: 0.2
        -
            id: 431
            damage: 6
            bulletId: 442
            maxBulletNum: 25
            knockback: 0.1
    #冲锋枪
        -
            id: 428
            damage: 3.5
            bulletId: 443
            maxBulletNum: 45
            knockback: 0.1
    #狙击枪
        -
            id: 430
            damage: 12
            bulletId: 446
            maxBulletNum: 10
            knockback: 0.2
        -
            id: 432
            damage: 18
            bulletId: 446
            maxBulletNum: 5
            knockback: 0.15
        -
            id: 434
            damage: 24
            bulletId: 446
            maxBulletNum: 5
            knockback: 0.1
    #加特林
        -
            id: 433
            damage: 8
            bulletId: 442
            maxBulletNum: 100
            knockback: 0.5
    bullet:
        -
            id: 441
            capacity: 64
        -
            id: 442
            capacity: 64
        -
            id: 443
            capacity: 64
        -
            id: 446
            capacity: 64

score:
    ticket: 1
    captureCriminal: 3
    killPolice: 5
    criminalIncident: 1
    
#广告配置 
respawnAdMaxTimes: 999
shopAdRefreshTime: 1800
