# produce will refresh in game 
# 监狱球场范围x = 366到409, y = 63到64，z = 280到349
produce:
    -
        id: 340
        num: 2
        life: 12
        interval: [10, 10]
        blockType: []
        x: [366, 387]
        y: [63, 64]
        z: [298, 314]
    -
        id: 340
        num: 2
        life: 12
        interval: [10, 10]
        blockType: []
        x: [366, 387]
        y: [63, 64]
        z: [280, 296]
    -
        id: 340
        num: 2
        life: 12
        interval: [10, 10]
        blockType: []
        x: [366, 387]
        y: [63, 64]
        z: [315, 331]
    -
        id: 340
        num: 2
        life: 12
        interval: [10, 10]
        blockType: []
        x: [366, 387]
        y: [63, 64]
        z: [333, 349]
    -
        id: 340
        num: 2
        life: 12
        interval: [10, 10]
        blockType: []
        x: [388, 409]
        y: [63, 64]
        z: [298, 314]
    -
        id: 340
        num: 2
        life: 12
        interval: [10, 10]
        blockType: []
        x: [388, 409]
        y: [63, 64]
        z: [280, 296]
    -
        id: 340
        num: 2
        life: 12
        interval: [10, 10]
        blockType: []
        x: [388, 409]
        y: [63, 64]
        z: [315, 331]
    -
        id: 340
        num: 2
        life: 12
        interval: [10, 10]
        blockType: []
        x: [388, 409]
        y: [63, 64]
        z: [333, 349]
    -
        id: 340
        num: 2
        life: 12
        interval: [10, 10]
        blockType: []
        x: [334, 340]
        y: [63, 64]
        z: [288, 294]
    -
        id: 340
        num: 2
        life: 12
        interval: [10, 10]
        blockType: []
        x: [279, 292]
        y: [63, 64]
        z: [272, 279]
    -
        id: 340
        num: 3
        life: 12
        interval: [10, 10]
        blockType: []
        x: [278, 287]
        y: [63, 64]
        z: [338, 350]
    -
        id: 340
        num: 2
        life: 12
        interval: [10, 10]
        blockType: []
        x: [277, 288]
        y: [63, 64]
        z: [315, 324]
    -
        id: 340
        num: 2
        life: 12
        interval: [10, 10]
        blockType: []
        x: [292, 298]
        y: [63, 64]
        z: [355, 360]
    -
        id: 340
        num: 2
        life: 12
        interval: [10, 10]
        blockType: []
        x: [277, 288]
        y: [63, 64]
        z: [315, 324]
    -
    # 禁闭室钥匙
        id: 452
        num: 1
        life: 8
        interval: [25, 40]
        blockType: []
        x: [318, 320]
        y: [70, 72]
        z: [251, 254]